version: '3.8'

services:
  postgraphile:
    build:
      context: .
      dockerfile: postgraphile.Dockerfile
    environment:
      POSTGRES_USER: pocket
      POSTGRES_PASSWORD: pocket
      POSTGRES_DB: pocket
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    depends_on:
      - postgres
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U pocket" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  # Use via `yarn migrate` (see: package.json scripts)
  migrate:
    build:
      context: .
      dockerfile: migrate.Dockerfile
    command: "migrate"
    environment:
      DATABASE_URL: postgres://pocket:pocket@postgres:5432/pocket
      SHADOW_DATABASE_URL: postgres://pocket:pocket@postgres:5432/pocket_shadow
      ROOT_DATABASE_URL: postgres://pocket:pocket@postgres:5432/postgres
#    user: "${UID}:${GID}"
    volumes:
      - "./:/app"
    depends_on:
      - postgres
  #    healthcheck:
  #      test: [ "CMD-SHELL", "pg_isready -U pocket" ]
  #      interval: 5s
  #      timeout: 5s
  #      retries: 5

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: pocket
      POSTGRES_PASSWORD: pocket
      POSTGRES_DB: pocket
#    user: "${UID}:${GID}"
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - "5432:5432"
